---
- name: clear out target directory
  file:
   state: absent
   path: "{{ document_root }}/"
  when:
  - "{{ purge|default('false') }} == true"

- name: ensure target directory exists
  become: yes
  file:
   state: directory
   path: "{{ document_root }}"
   mode: 0755
- name: copy other files
  become: yes
  copy:
    src: "{{ item }}"
    dest: "{{ document_root }}/"
  with_items:
    - css
    - scss
    - fonts
    - img
    - js
    - buttons
- name: create index.html
  become: yes
  template:
    src: index.html.j2
    dest: "{{ document_root }}/index.html"
